/**
 * SeedCampusMap.gs - GENERATED by scripts/campus-map/run.mjs (npm run campus-map). Do not edit by hand.
 * The operator's edits go to data/overrides (admin: NavNodes access, Buildings levels/height).
 */

/**
 * The automatic access class of each exterior door (scripts/campus-map/build.mjs autoEntranceAccess): the doors the
 * primary-entrance heuristic chose (scripts/floorplan-pipeline/stages/primary-entrances.mjs) main, stair-tower exits
 * emergency, the rest alt.
 * @return {Object} 19 NavNodes ids -> "main" | "alt" | "emergency"
 */
function getGeneratedEntranceAccess() {
  return {
    "ep-1-n0356": "alt",
    "ep-1-n0358": "main",
    "ep-1-n0359": "emergency",
    "ep-1-n0362": "main",
    "ep-1-n0363": "main",
    "ep-1-n0364": "alt",
    "ep-1-n0365": "alt",
    "ep-1-n0366": "alt",
    "it-1-n0489": "alt",
    "it-1-n0490": "main",
    "it-1-n0492": "main",
    "it-1-n0493": "alt",
    "it-1-n0494": "alt",
    "it-1-n0495": "alt",
    "it-2-n0551": "alt",
    "it-2-n0552": "main",
    "it-2-n0553": "alt",
    "it-2-n0554": "main",
    "it-2-n0557": "alt"
  };
}

/**
 * Per building: [levels, height]. levels from OpenStreetMap (building:levels, else height / 3.5 m) or the default by
 * type (academic 3, residence 4, other 2); height (m) only where OpenStreetMap gives one, else ''.
 * @return {Object} buildingId -> [levels, height]
 */
function getGeneratedBuildingLevels() {
  return {
    "bld-ac": [3,""],
    "bld-al": [3,""],
    "bld-as": [3,""],
    "bld-as-north": [3,""],
    "bld-as-south": [3,""],
    "bld-basketball-cts": [3,""],
    "bld-bauernfeind": [3,""],
    "bld-bb": [3,""],
    "bld-bg": [3,""],
    "bld-bl": [3,""],
    "bld-burton-hoc": [3,""],
    "bld-cb": [3,""],
    "bld-cc": [3,""],
    "bld-cc100": [4,""],
    "bld-cc1000": [4,""],
    "bld-cc1100": [4,""],
    "bld-cc1200": [4,""],
    "bld-cc200": [4,""],
    "bld-cc300": [4,""],
    "bld-cc400": [4,""],
    "bld-cc500": [4,""],
    "bld-cc600": [4,""],
    "bld-cc700": [4,""],
    "bld-cc800": [4,""],
    "bld-central-plant": [3,""],
    "bld-cf": [3,""],
    "bld-cfsb": [3,""],
    "bld-ch": [3,""],
    "bld-cherry-expo": [3,""],
    "bld-chickfila": [3,""],
    "bld-ck": [4,""],
    "bld-cp": [3,""],
    "bld-ct": [4,""],
    "bld-diamond-sports": [3,""],
    "bld-eagle-gallery": [3,""],
    "bld-el": [4,""],
    "bld-ep": [3,""],
    "bld-fa": [9,""],
    "bld-facilities": [3,""],
    "bld-fh": [3,""],
    "bld-fr": [4,""],
    "bld-gage-track": [3,""],
    "bld-golf": [3,""],
    "bld-ha": [3,""],
    "bld-he": [4,""],
    "bld-heritage": [4,""],
    "bld-hogancamp": [3,""],
    "bld-ht": [4,""],
    "bld-intramural": [3,""],
    "bld-it": [3,""],
    "bld-johnson-theatre": [3,""],
    "bld-la": [3,""],
    "bld-lc": [3,""],
    "bld-learning-commons": [3,""],
    "bld-mh": [3,""],
    "bld-nash": [3,""],
    "bld-nursing": [3,""],
    "bld-oakhurst": [3,""],
    "bld-old-fa": [3,""],
    "bld-pl": [3,""],
    "bld-police": [3,""],
    "bld-purcell-tennis": [3,""],
    "bld-quad": [3,""],
    "bld-racer-arena": [3,""],
    "bld-racer-field": [3,""],
    "bld-ray-center": [3,""],
    "bld-re": [4,""],
    "bld-reagan-field": [3,""],
    "bld-rifle-range": [3,""],
    "bld-rx": [4,""],
    "bld-sh": [3,""],
    "bld-sm": [3,""],
    "bld-sorority": [4,""],
    "bld-stadium-weight": [3,""],
    "bld-starbucks": [3,""],
    "bld-stewart-stadium": [3,""],
    "bld-tennis": [3,""],
    "bld-univ-club": [3,""],
    "bld-univ-store": [3,""],
    "bld-va": [3,""],
    "bld-we": [3,""],
    "bld-weaver": [3,""],
    "bld-wellness": [3,""],
    "bld-white": [4,""],
    "bld-wi": [3,""],
    "bld-winslow": [3,""],
    "bld-wl": [3,""],
    "bld-woods-park": [3,""],
    "bld-wr": [3,""]
  };
}
