// Stage "emit-gas": FP_<floorId>.html (raw <svg> per floor) and SeedFloorData.gs (row arrays in the header order of
// the v2 data contract: Floors, Rooms, NavNodes, NavEdges; v5 appends `access` to Rooms and NavNodes). The public
// floors go to tools/admin/gs; the hidden ones to the private location as SeedFloorDataPrivate.gs (PRIVATE_SEED), whose
// rows SeedData.gs appends to the public ones when the local admin loads that folder.
import fs from 'node:fs';
import path from 'node:path';
import { planAssetName } from '../config.mjs';
import { round } from '../lib/geometry.mjs';

export const HEADERS = {
  Floors: ['id', 'buildingId', 'level', 'label', 'planAsset', 'widthPx', 'heightPx', 'metersPerPixel', 'public'],
  Rooms: ['id', 'floorId', 'number', 'label', 'type', 'polygon', 'centerX', 'centerY', 'searchable', 'access'],
  NavNodes: ['id', 'floorId', 'x', 'y', 'type', 'roomId', 'linkId', 'access'],
  NavEdges: ['id', 'fromNodeId', 'toNodeId', 'distance', 'floorChange', 'accessible'],
};

export function floorRows(floors) {
  return floors.map((f) => [f.floorId, f.buildingId, f.level, f.label, f.planAsset, round(f.width, 1), round(f.height, 1), f.metersPerUnit, f.public]);
}

export function roomRows(floors) {
  const rows = [];
  for (const f of floors) {
    for (const r of f.rooms) {
      rows.push([r.id, f.floorId, r.number, r.label, r.type, JSON.stringify(r.polygon), r.center[0], r.center[1], r.searchable, r.type === 'corridor' ? 'main' : '']);
    }
  }
  return rows;
}

export function nodeRows(floors) {
  const rows = [];
  for (const f of floors) for (const n of f.nav.nodes) rows.push([n.id, f.floorId, n.x, n.y, n.type, n.roomId || '', n.linkId || '', n.access || '']);
  return rows;
}

export function edgeRows(floors, crossEdges) {
  const rows = [];
  for (const f of floors) for (const e of f.nav.edges) rows.push([e.id, e.from, e.to, e.distance, e.floorChange, e.accessible]);
  for (const e of crossEdges) rows.push([e.id, e.from, e.to, e.distance, e.floorChange, e.accessible]);
  return rows;
}

/** The seed file and its function names: the committed public seed, and the hidden floors' private seed. */
export const PUBLIC_SEED = {
  file: 'SeedFloorData.gs',
  fns: { Floors: 'getGeneratedFloorsSeed', Rooms: 'getGeneratedRoomsSeed', NavNodes: 'getGeneratedNavNodesSeed', NavEdges: 'getGeneratedNavEdgesSeed' },
  about: 'The public floors only: the hidden ones (config.mjs public: false) are written to the private location\n * (SeedFloorDataPrivate.gs, outside the repository).',
};
export const PRIVATE_SEED = {
  file: 'SeedFloorDataPrivate.gs',
  fns: { Floors: 'getPrivateFloorsSeed', Rooms: 'getPrivateRoomsSeed', NavNodes: 'getPrivateNavNodesSeed', NavEdges: 'getPrivateNavEdgesSeed' },
  about: 'The hidden floors (public: false) and the cross-floor edges that touch them. Never committed: SeedData.gs\n * appends these rows to SeedFloorData.gs when the local admin loads the private location.',
};

function fnBody(name, header, rows, doc) {
  const lines = rows.map((r) => '    ' + JSON.stringify(r)).join(',\n');
  return `/**\n * ${doc}\n * Columns: ${header.join(', ')}\n * @return {Array<Array>} ${rows.length} rows\n */\nfunction ${name}() {\n  return [\n${lines}\n  ];\n}\n`;
}

export function buildSeedGs(floors, crossEdges, meta) {
  const kind = meta.seed || PUBLIC_SEED;
  const parts = [];
  parts.push(
    `/**\n * ${kind.file} - GENERATED by scripts/floorplan-pipeline/run.mjs. Do not edit by hand:\n` +
      ` * regenerate with \`npm run pipeline\` (source: the DWGs in MSCN_DWG_DIR).\n *\n` +
      ` * Coordinates are per-floor SVG units (DWG ${meta.unitName}, origin at the floor's extents, y down).\n` +
      ` * metersPerPixel = meters per SVG unit. polygon is a JSON string of [x, y] pairs.\n` +
      ` * ${kind.about}\n */\n`
  );
  parts.push(fnBody(kind.fns.Floors, HEADERS.Floors, floorRows(floors), 'Floors rows.'));
  parts.push(fnBody(kind.fns.Rooms, HEADERS.Rooms, roomRows(floors), 'Rooms rows (every AREA-ROOM and AREA-CHAS polygon).'));
  parts.push(fnBody(kind.fns.NavNodes, HEADERS.NavNodes, nodeRows(floors), 'NavNodes rows.'));
  parts.push(fnBody(kind.fns.NavEdges, HEADERS.NavEdges, edgeRows(floors, crossEdges), 'NavEdges rows (distance in meters; cross-floor edges last).'));
  return parts.join('\n');
}

export function emitGas(floors, crossEdges, gasDir, meta) {
  fs.mkdirSync(gasDir, { recursive: true });
  const written = [];
  for (const f of floors) {
    const file = path.join(gasDir, planAssetName(f.floorId) + '.html');
    fs.writeFileSync(file, f.svg);
    written.push(file);
  }
  const seed = buildSeedGs(floors, crossEdges, meta);
  const seedFile = path.join(gasDir, (meta.seed || PUBLIC_SEED).file);
  fs.writeFileSync(seedFile, seed);
  written.push(seedFile);
  return { written, seedBytes: Buffer.byteLength(seed) };
}
