// Stage "emit-gas": FP_<floorId>.html (raw <svg> per floor) and SeedFloorData.gs (row arrays in the header order of
// the v2 data contract: Floors, Rooms, NavNodes, NavEdges).
import fs from 'node:fs';
import path from 'node:path';
import { planAssetName } from '../config.mjs';
import { round } from '../lib/geometry.mjs';

export const HEADERS = {
  Floors: ['id', 'buildingId', 'level', 'label', 'planAsset', 'widthPx', 'heightPx', 'metersPerPixel', 'public'],
  Rooms: ['id', 'floorId', 'number', 'label', 'type', 'polygon', 'centerX', 'centerY', 'searchable'],
  NavNodes: ['id', 'floorId', 'x', 'y', 'type', 'roomId', 'linkId'],
  NavEdges: ['id', 'fromNodeId', 'toNodeId', 'distance', 'floorChange', 'accessible'],
};

export function floorRows(floors) {
  return floors.map((f) => [f.floorId, f.buildingId, f.level, f.label, f.planAsset, round(f.width, 1), round(f.height, 1), f.metersPerUnit, f.public]);
}

export function roomRows(floors) {
  const rows = [];
  for (const f of floors) {
    for (const r of f.rooms) {
      rows.push([r.id, f.floorId, r.number, r.label, r.type, JSON.stringify(r.polygon), r.center[0], r.center[1], r.searchable]);
    }
  }
  return rows;
}

export function nodeRows(floors) {
  const rows = [];
  for (const f of floors) for (const n of f.nav.nodes) rows.push([n.id, f.floorId, n.x, n.y, n.type, n.roomId || '', n.linkId || '']);
  return rows;
}

export function edgeRows(floors, crossEdges) {
  const rows = [];
  for (const f of floors) for (const e of f.nav.edges) rows.push([e.id, e.from, e.to, e.distance, e.floorChange, e.accessible]);
  for (const e of crossEdges) rows.push([e.id, e.from, e.to, e.distance, e.floorChange, e.accessible]);
  return rows;
}

function fnBody(name, header, rows, doc) {
  const lines = rows.map((r) => '    ' + JSON.stringify(r)).join(',\n');
  return `/**\n * ${doc}\n * Columns: ${header.join(', ')}\n * @return {Array<Array>} ${rows.length} rows\n */\nfunction ${name}() {\n  return [\n${lines}\n  ];\n}\n`;
}

export function buildSeedGs(floors, crossEdges, meta) {
  const parts = [];
  parts.push(
    `/**\n * SeedFloorData.gs - GENERATED by scripts/floorplan-pipeline/run.mjs. Do not edit by hand:\n` +
      ` * regenerate with \`npm run pipeline\` (source: data/dwg/*.dwg).\n *\n` +
      ` * Coordinates are per-floor SVG units (DWG ${meta.unitName}, origin at the floor's extents, y down).\n` +
      ` * metersPerPixel = meters per SVG unit. polygon is a JSON string of [x, y] pairs.\n` +
      ` * Floors 3 (IT mezzanine, EP penthouse) are public: false.\n */\n`
  );
  parts.push(fnBody('getGeneratedFloorsSeed', HEADERS.Floors, floorRows(floors), 'Floors rows.'));
  parts.push(fnBody('getGeneratedRoomsSeed', HEADERS.Rooms, roomRows(floors), 'Rooms rows (every AREA-ROOM and AREA-CHAS polygon).'));
  parts.push(fnBody('getGeneratedNavNodesSeed', HEADERS.NavNodes, nodeRows(floors), 'NavNodes rows.'));
  parts.push(fnBody('getGeneratedNavEdgesSeed', HEADERS.NavEdges, edgeRows(floors, crossEdges), 'NavEdges rows (distance in meters; cross-floor edges last).'));
  return parts.join('\n');
}

export function emitGas(floors, crossEdges, gasDir, meta) {
  fs.mkdirSync(gasDir, { recursive: true });
  const written = [];
  for (const f of floors) {
    const file = path.join(gasDir, planAssetName(f.floorId) + '.html');
    fs.writeFileSync(file, f.svg);
    written.push(file);
  }
  const seed = buildSeedGs(floors, crossEdges, meta);
  const seedFile = path.join(gasDir, 'SeedFloorData.gs');
  fs.writeFileSync(seedFile, seed);
  written.push(seedFile);
  return { written, seedBytes: Buffer.byteLength(seed) };
}
